/**
 * Vendor the unit silhouettes from game-icons.net as path data.
 *
 * Run with `pnpm tsx apps/web/scripts/unit-art.ts`. Fetches each icon named in `UNIT_ART_CREDITS`
 * as a black-on-transparent SVG, keeps only its path, and writes `src/lib/unitArtPaths.ts`. The
 * icons are CC BY 3.0; the credits live next to the mapping and on the About page.
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { UNIT_ART_CREDITS, UNIT_ART_IDS, UNIT_ART_SOURCE, type UnitArtId } from "../src/lib/unitArt";

const OUT = resolve(fileURLToPath(new URL(".", import.meta.url)), "../src/lib/unitArtPaths.ts");

async function fetchPath(slug: string): Promise<string> {
  const url = `${UNIT_ART_SOURCE.url}/icons/000000/transparent/1x1/${slug}.svg`;
  const res = await fetch(url, { headers: { "user-agent": "grimstat-unit-art (https://github.com/N041M/Grimstat)" } });
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  const svg = await res.text();
  // One icon is one path; the site's wrapper adds a background rect only when a colour is asked for.
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]!);
  if (paths.length === 0) throw new Error(`${url}: no path found`);
  return paths.join(" ");
}

const entries: string[] = [];
for (const id of UNIT_ART_IDS as readonly UnitArtId[]) {
  const credit = UNIT_ART_CREDITS[id];
  const d = await fetchPath(credit.slug);
  entries.push(`  ${JSON.stringify(id)}: ${JSON.stringify(d)},`);
  console.log(`${id.padEnd(14)} ${credit.slug.padEnd(28)} ${d.length} chars`);
}

writeFileSync(
  OUT,
  `/**
 * Path data for the unit silhouettes. GENERATED by \`apps/web/scripts/unit-art.ts\` — do not edit;
 * run the script to refresh. Each entry is the \`d\` of one game-icons.net icon on a 512 × 512
 * canvas, credited in \`unitArt.ts\` and on the About page (CC BY 3.0).
 */

import type { UnitArtId } from "./unitArt";

export const UNIT_ART_PATHS: Readonly<Record<UnitArtId, string>> = {
${entries.join("\n")}
};
`,
);
console.log(`wrote ${OUT}`);
